#!/bin/bash

echo "==================================================================="
echo "SUPERSHIFT LABS - STORAGE SETUP INSTRUCTIONS"
echo "==================================================================="
echo ""
echo "The storage upload error you're seeing is because the Supabase"
echo "storage bucket 'shift-admin' doesn't have proper RLS policies."
echo ""
echo "🔧 IMMEDIATE FIX REQUIRED:"
echo ""
echo "1. Go to your Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/pjhrogdbzpqnxhfxxmsb"
echo ""
echo "2. Navigate to: Storage → Policies"
echo ""
echo "3. Create these 4 policies for the 'shift-admin' bucket:"
echo ""
echo "   Policy 1: Allow authenticated uploads"
echo "   - Name: Allow authenticated uploads to shift-admin"
echo "   - Operation: INSERT"
echo "   - Target roles: authenticated"
echo "   - USING expression: bucket_id = 'shift-admin'"
echo "   - WITH CHECK expression: bucket_id = 'shift-admin'"
echo ""
echo "   Policy 2: Allow public viewing"
echo "   - Name: Allow public access to shift-admin"
echo "   - Operation: SELECT"
echo "   - Target roles: public"
echo "   - USING expression: bucket_id = 'shift-admin'"
echo ""
echo "   Policy 3: Allow authenticated updates"
echo "   - Name: Allow authenticated updates to shift-admin"
echo "   - Operation: UPDATE"
echo "   - Target roles: authenticated"
echo "   - USING expression: bucket_id = 'shift-admin'"
echo "   - WITH CHECK expression: bucket_id = 'shift-admin'"
echo ""
echo "   Policy 4: Allow authenticated deletes"
echo "   - Name: Allow authenticated deletes from shift-admin"
echo "   - Operation: DELETE"
echo "   - Target roles: authenticated"
echo "   - USING expression: bucket_id = 'shift-admin'"
echo ""
echo "4. After creating policies, create admin account:"
echo "   - Visit /admin on your site"
echo "   - Sign up with: dirkawspy@gmail.com"
echo "   - Confirm email and sign in"
echo ""
echo "5. Test file upload in admin dashboard"
echo ""
echo "==================================================================="
echo "Once completed, file uploads will work without errors!"
echo "==================================================================="
